services:
  user:
    image: ghcr.io/0xdeadcat/userservice:main
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: rabbitmq
  relay:
    image: ghcr.io/0xdeadcat/relayservice:main
    depends_on:
      - rabbitmq
      - proxy
  frontend:
    image: ghcr.io/dobja/frontendservice:main
    depends_on:
      - relay
      - proxy
  chat:
    image: ghcr.io/dobja/chatservice:main
    depends_on:
      - rabbitmq
  proxy:
    build: proxy
    ports:
      - "80:80"
      - "8080:8080"
    

volumes:
  postgres-data:
  driver:
    name: local