version: '3.8'

services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    hostname: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  proxy:
    image: nginx:1.21.6-alpine
    volumes:
      - ./proxy:/etc/nginx/templates
    ports:
      - "80:80"
    env_file:
      - proxy.env

  frontend:
    image: ghcr.io/dobja/chatfrontend:v2.1.0
    env_file:
      - common.env

  relay:
    image: ghcr.io/0xdeadcat/relayservice:v2.1.0
    env_file:
      - common.env

  chat:
    image: ghcr.io/dobja/chatservice:v2.1.0
    env_file:
      - common.env
      - chat.env

  user:
    image: ghcr.io/0xdeadcat/userservice:v2.0.0
    env_file:
      - common.env
      - user.env