services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  proxy:
    build: proxy
    ports:
      - "80:80"
      - "8080:8080"
      - "8081:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
  frontend:
    image: ghcr.io/dobja/chatfrontend:main
    depends_on:
      - proxy
  relay:
    image: ghcr.io/0xdeadcat/relayservice:main
    depends_on:
      rabbitmq:
        condition: service_healthy
  chat:
    image: ghcr.io/dobja/chatservice:main
    depends_on:
      rabbitmq:
        condition: service_healthy
  user:
    image: ghcr.io/0xdeadcat/userservice:main
    depends_on:
      - postgres
    

volumes:
  postgres-data:
  driver:
    name: local